### ISSUE TITLE
Is a screenshot available?

### ISSUE THREAD

**Issue by PySimpleGUI** [Martin199X/Network-Security-EVTX-Log-Analyser#2]
Would love to see a screenshot of your application.  I'm sure visitors would be quite interested if you added one to your readme.

**Comment by martinmathurine** [comment]
I will add screenshots of my application as you suggested.

**Comment by PySimpleGUI** [comment]
![image](https://user-images.githubusercontent.com/46163555/234085138-4f10eb0f-c251-442a-928e-86540c22f705.png)

Awesome!

**Comment by martinmathurine** [comment]
I have updated the Network Security EVTX Log Analyser's readme.md file to incorporate a visual user guide.

**Comment by PySimpleGUI** [comment]
![image](https://user-images.githubusercontent.com/46163555/234340318-e67156f6-9b03-40f3-8f85-3c6353ef6a81.png)

WOW!  Those are nice.  You've even got tooltips in them.  Thank you very much for taking the time to add them.
